name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Build the Docker image
      run: docker build -t Linear-Regression_Flask .
    - name: Get the version
      id: vars
      run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
    - name: Build the tagged Docker image
      run: docker tag Linear-Regression_Flask ${{ secrets.DOCKERHUB_USERNAME }}/Linear-Regression_Flask:latest
    - name: Push the latest Docker image
      run: docker push  ${{ secrets.DOCKERHUB_USERNAME }}/Linear-Regression_Flask
