name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Build the Docker image
      run: docker build -t Linear-Regression_Flask .
    - name: Push the latest Docker image
      run: docker push  ${{ secrets.DOCKERHUB_USERNAME }}/Linear-Regression_Flask
