name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Build the Docker image
      run: docker build -t wscv0592/docker-project-1 .
    - name: Get the version
      id: vars
      run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
    - name: Build the tagged Docker image
      run: docker tag docker-project-1 ${{ secrets.DOCKERHUB_USERNAME }}/docker-project-1:latest
    - name: Push the latest Docker image
      run: docker push  ${{ secrets.DOCKERHUB_USERNAME }}/docker-project-1
